# Generated by Django 5.2 on 2025-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DermatoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('total_body', 'Total Body Mapping'), ('head_neck', 'Head & Neck'), ('torso', 'Torso'), ('upper_ext', 'Upper Extremities'), ('lower_ext', 'Lower Extremities'), ('global', 'Global View'), ('regional', 'Regional View'), ('closeup', 'Close-up Dermoscopy')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
